name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.17.x, 14.x.x, 16.6.x, 17.x, 18.x, 19.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: node common/scripts/install-run-rush install

      - name: Build and test
        run: |
          node common/scripts/install-run-rush build
          node common/scripts/install-run-rush lint
          node common/scripts/install-run-rush test --coverage
