name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.13.x, 12.16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use rushjs
        run: npm i -g @microsoft/rush

      - name: Install
        run: rush update

      - name: Build and test
        run: |
          rush build
          rush lint
          rush test --coverage
